### ISSUE TITLE
Error: Cannot parse 2022-08-10+19:23:39 as a valid ISO-8601 date

### ISSUE THREAD

**Issue by vin** [jwoglom/tconnectsync-heroku#12] opened 2022-08-11 19:28 UTC
I just deployed  tconnectsync-heroku v0.8.1 and my logs are showing:

```
call output: No last CGM reading is able to be determined from CIQ
2022-08-11T19:23:48.750232+00:00 app[web.1]: Downloading t:connect CSV data
2022-08-11T19:23:48.750233+00:00 app[web.1]: Falling back on WS2 CSV data source because BOLUS is an enabled feature and CIQ bolus data was empty!!
2022-08-11T19:23:48.750233+00:00 app[web.1]: <!!> The WS2 data source is unreliable and may prevent timely synchronization
2022-08-11T19:23:48.750233+00:00 app[web.1]: No last CGM reading is able to be determined from CSV
2022-08-11T19:23:48.750234+00:00 app[web.1]: Traceback (most recent call last):
2022-08-11T19:23:48.750234+00:00 app[web.1]:   File "/app/utils.py", line 22, in call
2022-08-11T19:23:48.750234+00:00 app[web.1]:     fn(*args, **kwargs)
2022-08-11T19:23:48.750235+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/tconnectsync/process.py", line 143, in process_time_range
2022-08-11T19:23:48.750235+00:00 app[web.1]:     added += ns_write_basal_events(nightscout, basalEvents, pretend=pretend, time_start=time_start, time_end=time_end)
2022-08-11T19:23:48.750235+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/tconnectsync/sync/basal.py", line 109, in ns_write_basal_events
2022-08-11T19:23:48.750236+00:00 app[web.1]:     last_upload = nightscout.last_uploaded_entry(BASAL_EVENTTYPE, time_start=time_start, time_end=time_end)
2022-08-11T19:23:48.750236+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/tconnectsync/nightscout.py", line 64, in last_uploaded_entry
2022-08-11T19:23:48.750236+00:00 app[web.1]:     raise ApiException(latest.status_code, "Nightscout last_uploaded_entry response: %s" % latest.text)
2022-08-11T19:23:48.750237+00:00 app[web.1]: tconnectsync.api.common.ApiException: Nightscout last_uploaded_entry response: <html>
2022-08-11T19:23:48.750237+00:00 app[web.1]:   <head>
2022-08-11T19:23:48.750238+00:00 app[web.1]:     <meta charset='utf-8'> 
2022-08-11T19:23:48.750238+00:00 app[web.1]:     <title>Error: Cannot parse 2022-08-10+19:23:39 as a valid ISO-8601 date</title>
2022-08-11T19:23:48.750238+00:00 app[web.1]:     <style>* {
2022-08-11T19:23:48.750238+00:00 app[web.1]:   margin: 0;
2022-08-11T19:23:48.750238+00:00 app[web.1]:   padding: 0;
2022-08-11T19:23:48.750238+00:00 app[web.1]:   outline: 0;
2022-08-11T19:23:48.750239+00:00 app[web.1]: }
[...]
```

(truncated -- it's an entire HTML error page)

I think this is new since v0.8.1. With v0.7.1 I see:

```
2022-08-11T19:27:13.067348+00:00 app[web.1]: call args: [<tconnectsync.api.TConnectApi object at 0x7fb997a80790>, <tconnectsync.nightscout.NightscoutApi object at 0x7fb997a807c0>, datetime.datetime(2022, 8, 10, 19, 27, 13, 67042), datetime.datetime(2022, 8, 11, 19, 27, 13, 67042), False, ['BOLUS', 'BASAL', 'PUMP_EVENTS']]
```

without the parse error I see in 0.8.

**Comment by jwoglom** [comment] 2022-08-11 21:50
I'll look into this, it was likely caused by some refactoring changes that broke how datetimes are sent to Nightscout.

**Comment by jwoglom** [comment] 2022-08-12 05:32
@vin What Nightscout version are you using? And can you go to the tconnectsync test_login URL and copy-and-paste its contents, either post them here as a comment or email me (my email address is on my GitHub profile). https://github.com/jwoglom/tconnectsync-heroku#testing

**Comment by jip2587** [comment] 2022-08-15 19:33
I tried to install today, and am running into this same issue.

**Comment by jwoglom** [comment] 2022-08-15 20:06
@vin @jip2587 would you be able to download the entirety of your tconnectsync logs through Heroku? I'm trying to track down exactly where tconnectsync is saving an entry with the wrong timestamp inside Nightscout. You can email me at the address on my GitHub profile.

**Comment by jip2587** [comment] 2022-08-15 20:31
So actually, I think I got a little confused as I've tried multiple ways to get this working today. 

When using the Heroku version, the check-login is giving me a 403 forbidden error. It's when I use tconnect-sync --auto-update on a pip3 install that I'm getting this ISO date error. That said, I'll try to send you logs from both here in a bit.

**Comment by jwoglom** [comment] 2022-08-24 16:32
This should be resolved in https://github.com/jwoglom/tconnectsync/pull/51, update to the latest version of tconnectsync-heroku to get the fix.

**Closed by jwoglom** 2022-08-24 16:32 UTC
